### ISSUE TITLE
Enhance nginx_conf page to include 'how to add symbolic link for rails apps'

### ISSUE THREAD

**Issue by krand7** [remomueller/documentation#6]
This should give someone a sense of how to set up nginx for their own rails app. Could link to similar information in https://github.com/sleepepi/sleepepi/blob/master/virtual-machines/173-nginx-configuration.md

**Comment by remomueller** [comment]
It looks like both the [centos](https://github.com/remomueller/documentation/blob/master/centos/170-install-nginx.md) and [macos](https://github.com/remomueller/documentation/blob/master/macos/173-nginx-configuration.md) instructions have a reference to setting up symbolic links commented out in the nginx.conf files.
